version: '1.0'
name: master-hookform-pipeline
displayName: MuiExtHookFormMasterPipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - master
    commitMessages:
      include:
        - '^build\(hookform\)\:.*'
variables:
  global:
    - NPM_TOKEN
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 16.14.1
        commands:
          - npm install pnpm @jsdevtools/npm-publish -g
          - pnpm install
          - cd packages/hookform
          - rm -rf ./dist && pnpm build
          - test -f ./dist/index.js && npm-publish --token=${NPM_TOKEN} ./package.json
