version: '1.0'
name: master-core-pipeline
displayName: MuiExtCoreMasterPipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - master
    commitMessages:
      include:
        - '^build\(core\)\:.*'
variables:
  global:
    - NPM_TOKEN
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 15.12.0
        commands:
          - npm install pnpm @jsdevtools/npm-publish npm@9.3.1 -g
          - cd packages/core
          - pnpm install && rm -rf ./dist && pnpm build
          - test -f ./dist/index.js
